// <auto-generated />
namespace OnlineStoreDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class deleteshoppingcart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteshoppingcart));
        
        string IMigrationMetadata.Id
        {
            get { return "202108100605315_delete shopping cart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
